# Generated by Django 4.1.7 on 2023-03-09 15:17

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
